config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

ItMgmt::Application.routes.draw do


  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}#, path_names: {sign_in: "login", sign_out: "logout"}
  resources :incidentes
  resources :grupos
  # resources :comandos_automacaos
  resources :softwares

  # resources :inventario
  get "/inventario", to: "inventario#index", as: "inventario"
  get "/inventario/:id", to: "inventario#show", as: "get_inventario"
  get "/inventario/:id/:acao", to: "inventario#acao", as: "acao_inventario"
  post "/inventario", to: "inventario#confirma", as: "confirmar_inventario"
  

  
  get "Licencas/PorGestor/:id(/:versao)", to: "licencas#porGestor", as: "LicencasPorGestor" , :constraints => { :id => /[a-zA-z0-9.]*/ }

  get "Licencas/PorUsuario/:id", to: "licencas#porUsuario", as: "LicencasPorUsuario" , :constraints => { :id => /.*/ }


  get "identities/:id", to: "identities#show", as: "identities" , :constraints => { :id => /.*/ }

  # post "ws_register_desligamento", to: "log_desligamento#ws_register_desligamento"
  resources :users , except: :new
  get 'users_perfil', to: "users#show_perfil"
  resources :schedulers
  post "schedulers/:id/run", to: "schedulers#run", as: "scheduler_run"
  resources :producaos , :only => [:index]

  get "painel_producao/:id/(:scope)" , to:"painel_producao#index", as: "painel_producao"

  get "GestaoUsuarios", to: "gestao_usuarios#index", as: "gestao_usuarios", :constraints => { :id => /.*/ }

  get 'GestaoUsuarios/:id/email', to: "gestao_usuarios#email", :constraints => { :id => /.*/ },  :as => :email_gestao_usuario
  post 'GestaoUsuarios/:id/email', to: "gestao_usuarios#enviar_email", :constraints => { :id => /.*/ },  :as => :enviar_email_gestao_usuario

  post "GestaoUsuarios/AlocarEstacao",  to: "gestao_usuarios#alocar_estacao", as: "alocar_estacao"
  get "GestaoUsuarios/EscolherLicencaAlocar",  to: "gestao_usuarios#escolher_licenca_alocar", as: "escolher_licenca_alocar"
  get "GestaoUsuarios/EscolherEstacaoAlocar",  to: "gestao_usuarios#escolher_estacao_alocar", as: "escolher_estacao_alocar"
  get "GestaoUsuarios/:id/confirmardesalocarestacao/:estacao", to: "gestao_usuarios#confirmar_desalocar_estacao", as: "confirmar_desalocar_estacao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermoentrega/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_entrega", as: "imprimir_termo_entrega", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermodevolucao/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_devolucao", as: "imprimir_termo_devolucao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/confirmarremocaolicenca/:licenca", to: "gestao_usuarios#confirmar_remocao_licenca", as: "confirmar_remocao_licenca", :constraints => { :id => /.*/ }
  post "GestaoUsuarios/AlocarLicenca", to: "gestao_usuarios#alocar_licenca", as: "alocar_licenca"
  post "GestaoUsuarios/deletelicenca", to: "gestao_usuarios#remover_licenca", as: "remover_licenca"
  post "GestaoUsuarios/DesalocarEstacao", to: "gestao_usuarios#desalocar_estacao", as: "desalocar_estacao"

  resources :funcionarios , :constraints => { :id => /.*/ }
  get 'equipe/:id', to: "funcionarios#equipe", :constraints => { :id => /.*/ }, as: "equipe"

  get "ajax/cis"
  get "ajax/gestores"

  resources :custom_de_paras
  resources :events, :only => [:index]

  resources :mailings
  get  "mailings/enviar_email", to: "mailings#enviar_email"
  post "mailings/enviar_email_sql", to: "mailings#enviar_email_sql"
  post "mailings/confirma_enviar_email", to: "mailings#confirma_enviar_email"
  post "mailings/confirma_enviar_email_sql", to: "mailings#confirma_enviar_email_sql"

  resources :notes

  resources :status_incidentes

  resources :templates_emails

  resources :sql_templates

  root "cis#index"

  mount Sidekiq::Web, at: '/sidekiq' ,  :constraints => AdminConstraint.new(:manage, :sidekiq)

  resources :ramal, :only => [:index]
 
  resources :audits
  # resources :atributos


  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :cadrelatorios
  match 'cadrelatorios/:id/duplicar', to: "cadrelatorios#duplicar", :as => :duplicar_relatorio, via: [:get, :post]

  resources :statuscis

  match 'relatorio_publico/:id', to: "relatorio#index", as: "relatorio", via: [:get, :post]
  match 'relatorio/:id', to: "relatorio#index_publico", as: "relatorio_publico", via: [:get, :post]
  match 'email/:acao/:id', to: "email#enviar", via: [:get, :post]
  match 'email/enviar_email/:id', to: "email#enviar+email", via: [:get, :post]

  match '/tasks/todos', to: 'tasks#todos', via: [:get, :post]
  match '/cis/todos', to: 'cis#todos', via: [:get, :post]

  match '/tasks/:id/new_from_ci', to: 'tasks#new_from_ci', as: "tasks_new_from_ci", via: [:get, :post]

  resources :parametros #, :only => [:index,:edit,:update,:new]
  match 'parametros/:id/duplicar', to: "parametros#duplicar", :as => :duplicar_parametro, via: [:get, :post]

  resources :dicdados
  match 'dicdados/:id/duplicar', to: "dicdados#duplicar", :as => :duplicar_dicdado, via: [:get, :post]


  get 'cis/:id/email', to: "cis#email",  :as => :email
  post 'cis/:id/email', to: "cis#enviar_email",  :as => :enviar_email  #, defaults: { format: 'js' }
  get "cis/:id/log", to: "cis#log", as: "log_ci"
  post 'cis/:id/log', to: "cis#register_log",  :as => :register_log

  get 'cis/:id/impactados', to: "cis#impactados",  :as => :impactados
  get 'cis/:id/dependentes', to: "cis#dependentes",  :as => :dependentes
  get 'cis/:id/dependentes_all', to: "cis#dependentes_all",  :as => :dependentes_all
  get 'cis/:id/grafico_impactados', to: "cis#grafico_impactados",  :as => :grafico_impactados
  get 'cis/:id/impactados_h', to: "cis#impactados_h", :as => :impactados_h
  get 'cis/:id/dependentes_h', to: "cis#dependentes_h", :as => :dependentes_h
  #get 'cis/:id/abrir_alerta', to: "cis#abrir_alerta", :as => :abrir_alerta

  post 'cis/:id/novo_dependente', to: "cis#gera_novo_dependente", :as => :gera_novo_dependente
  match 'cis/:id/novo_dependente', to: "cis#novo_dependente", :as => :novo_dependente, via: [:get, :post]
  post 'cis/:id/novo_impactado', to: "cis#gera_novo_impactado", :as => :gera_novo_impactado
  match 'cis/:id/novo_impactado', to: "cis#novo_impactado", :as => :novo_impactado, via: [:get, :post]

  post 'cis/:id/elimina_dependente', to: "cis#elimina_dependente", :as => :elimina_dependente
  match 'cis/:id/elimina_dependente', to: "cis#ask_elimina_dependente", :as => :ask_elimina_dependente, via: [:get, :post]
  post 'cis/:id/elimina_impactado', to: "cis#elimina_impactado", :as => :elimina_impactado
  match 'cis/:id/elimina_impactado', to: "cis#ask_elimina_impactado", :as => :ask_elimina_impactado, via: [:get, :post]

  post 'cis/:id/duplicar_ci', to: "cis#duplicar_ci", :as => :duplicar_ci
  match 'cis/:id/duplicar_ci', to: "cis#ask_duplicar_ci", :as => :ask_duplicar_ci, via: [:get, :post]
  

  match 'cis/:id/confirmar_eliminacao', to: "cis#confirmar_eliminacao", :as => :confirmar_eliminacao, via: [:get, :post]
  post 'cis/:id/cis_eliminar', to: "cis#eliminar", :as => :eliminar_ci
  match 'cis/checkChave', to: "cis#check_chave", via: [:get, :post]

  match 'cis/massiveupdate', to: "cis#massiveupdate", via: [:get, :post]

  # get '/cis/:id', to: "cis#show", :constraints => { :id => /.*/ }
  # match '/cis2', to: 'cis#index2'


  # get 'cis/search', to: "cis#search"
  get 'CMDB', to: "cis#index"

  resources :cis
  resources :criticidades

  resources :sites

  resources :tasks

  resources :categories

  resources :authors

  resources :console

  resources :tipocis

  get '/404' => 'errors#not_found'            , :via => :all
  get '/422' => 'errors#server_error'         , :via => :all
  get '/500' => 'errors#internal_server_error', :via => :all

  # get '*a', :to => 'cis#index'


end

app/models/scheduler.rb
class Scheduler < ActiveRecord::Base
  attr_accessible :job, :when, :ordem

  default_scope { order('ordem ASC') }

  def self.go
  	hoje = Time.now()
  	Scheduler.all.each do |x|
  		# if x.when[hoje]=="1" 
  		# 	Producao.dispatcherJob(x.job)
  		# end
  		if (((x.when.include? "[#{hoje.day}]") ||  (x.when.include? ["[dom]","[seg]","[ter]","[qua]","[qui]","[sex]","[sab]"][hoje.wday])) and x.when.include? "[H#{hoje.hour}]")
        puts x.job
  		 	Producao.dispatcherJob(x.job)
  		 end
 	end  	
  end
end

# "[seg],[ter],[qua],[sex],[17],[18]"
# 
# x.include? "[#{a.day}]"
# x.downcase.include? ["dom","seg","ter","qua","qui","sex","sab"][a.wday]

# Whenever 
#    Roda rake scheduler:go
# Rake scheduler:go 
#    roda Class Scheduler.go 
# Scheduler.go
#    Pesquisa no Scheduler, quais [job]s que tem para rodar naquele dia
#       Producao.dispatcher ([job])
#
# Producao.dispatcher
#     Criar um Producao (no db)
#     Enfilera no sidekiq Producao.id
#
# ProducaoWork
#     Case Job
#         executa servico equivalente ao token [job] , Ex: CargaPosicao

app/controllers/schedulers_controller.rb
class SchedulersController < InheritedResources::Base

load_and_authorize_resource
  before_filter :authenticate_user!

def run
	id = params[:id]
	job = Scheduler.find(id)
	Producao.dispatcherJob(job.job)
	flash[:info] = "INFO: Job [#{job.job}] enfileirado para execucao"
	@schedulers = Scheduler.all
	redirect_to :controller => 'schedulers', :action => 'index'
end
end

app/helpers/schedulers_helper.rb
module SchedulersHelper
	def SchedulerGenField(valor)
	    params = valor.split("_") 
        case params[0]
        when "Mailing"
            res = link_to(valor,"/relatorio/#{params[1]}",:target => "_blank" )
        when "Dashboard"
            res = link_to(valor,"/painel_producao/#{params[1]}",:target => "_blank" )
        else 
            res = valor
        end
        
        # 
        res = "" unless res

        res
	end


end

app/views/schedulers/_form.html.slim
.container
  .row
    div
      = form_for(@scheduler, :html => {:class => "panel-body #{controller.action_name}_scheduler"}) do |f|
        - if @scheduler.errors.any?
          #error_explanation
            h2
              = pluralize(@scheduler.errors.count, "erro" )
              |  ao tentar salvar esse Job:
            ul
              - @scheduler.errors.full_messages.each do |msg|
                li
                  = msg
        .form-group
          label[for="job"]
            | Nome do Job:
          = f.text_field :job, :maxlength=>50,  class: "form-control", autofocus: ""
        .form-group
          label[for="when"]
            | Quando Executar:
          = f.text_field :when, :maxlength=>50,  class: "form-control", placeholder: "[seg][ter][qua][qui][sex][sab][dom][H3] [20][H5]"
        .form-group
          label[for="ordem"]
            | Ordem:
          = f.text_field :ordem, :maxlength=>10,  class: "form-control", placeholder: "Ordem de apresentacao"
        button.btn.btn-primary.btn-md[type="submit"]
          |  Salvar Usuario 
        = link_to 'Cancelar', schedulers_path,  {:id => "Cancelar", :class => "btn btn-danger btn-md margin-left"}

app/views/schedulers/edit.html.erb
<% title "GAM. Editando Job Agendado: #{@scheduler.job}" %>
<%= render 'form' %>

app/views/schedulers/index.html.erb
<% title "GAM. Jobs Agendado" %><!-- <%= csrf_meta_tag %> -->
<script type="text/javascript">
$(document).ready( function(){
$('#coolTable').DataTable({
      pageLength: 100,
      pagingType: "full_numbers",
      language: { 
          search: "Filtrar:" ,
          infoFiltered: "(Total de _MAX_ registros)",
          info:   "Mostrando do registro _START_ até _END_ de um total de  _TOTAL_ filtrados",
          "lengthMenu":     "Mostrar _MENU_ registros",
          "paginate": {
              "first":      "Primeira",
              "last":       "Última",
              "next":       "Próxima",
              "previous":   "Anterior"
          },
          "infoEmpty":      "Mostrando do registro 0 até 0 de um total de 0 registros",
          "zeroRecords":    "Nenhum registro achado",
      }   
});
});
</script>
<div id="content">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= link_to 'Novo Job', new_scheduler_path, class: "btn btn-primary btn-xs" %>
    </div>
    <div class="panel-body">
      <table id="coolTable" class="generalTable"> <!-- class="generalTable" -->
      <thead>
        <tr class="head">
          <th>Ordem</th>
          <th>Job</th>
          <th>Quando</th>
          <% if (can? :manage, Scheduler)  %>
          <th></th>
          <% end %>
          
        </tr>
      </thead>
      <tbody>
        <% @schedulers.each do |scheduler| %>
        <tr>
          <td><%= scheduler.ordem %></td>
          <td><%= SchedulerGenField(scheduler.job) %></td>
          <td><%= scheduler.when %></td>
          
          <% if (can? :manage, Scheduler)  %>
          <td>
            <%= link_to 'Editar', edit_scheduler_path(scheduler), class: "btn btn-primary btn-xs" %>
            <%= link_to 'Rodar', scheduler_run_path(scheduler) ,method: :post, data: { confirm: 'Confirma executar esse job agora ?' } , class: "btn btn-success btn-xs"%>
            <%= tela_ajuda(scheduler.job, "btn btn-primary btn-xs")  %>
            <%= link_to 'Excluir', scheduler, method: :delete, data: { confirm: 'Tem certeza que deseja eliminar esse job ?' } , class: "btn btn-danger btn-xs"%>
          </td>
        </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div><!--  panel-body -->
</div>

app/views/schedulers/new.html.erb
<% title "GAM. Novo Job Agendado" %>
<%= render 'form' %>

app/views/schedulers/show.html.slim
- title "GAM. Job Agendado: #{@scheduler.job}"
.container
  .row
    / p#notice
    /   = notice
    .panel.panel-default.panel-primary
      .panel-body.panel-primary
        |  Job: 
        .list-group
          .list-group-item
            h4.list-group-item-heading
              | Job
            p.list-group-item-text
              = @scheduler.job

          .list-group-item
            h4.list-group-item-heading
              | Quando
            p.list-group-item-text
              = @scheduler.when
          .list-group-item
            h4.list-group-item-heading
              | Ordem
            p.list-group-item-text
              = @scheduler.ordem          
    = link_to 'Editar', edit_scheduler_path(@scheduler), :class => "btn btn-primary btn-md margin-left"
    = link_to 'Listagem', schedulers_path , :class => "btn btn-primary btn-md margin-left"