config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

ItMgmt::Application.routes.draw do


  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}#, path_names: {sign_in: "login", sign_out: "logout"}
  resources :incidentes
  resources :grupos
  # resources :comandos_automacaos
  resources :softwares

  # resources :inventario
  get "/inventario", to: "inventario#index", as: "inventario"
  get "/inventario/:id", to: "inventario#show", as: "get_inventario"
  get "/inventario/:id/:acao", to: "inventario#acao", as: "acao_inventario"
  post "/inventario", to: "inventario#confirma", as: "confirmar_inventario"
  

  
  get "Licencas/PorGestor/:id(/:versao)", to: "licencas#porGestor", as: "LicencasPorGestor" , :constraints => { :id => /[a-zA-z0-9.]*/ }

  get "Licencas/PorUsuario/:id", to: "licencas#porUsuario", as: "LicencasPorUsuario" , :constraints => { :id => /.*/ }


  get "identities/:id", to: "identities#show", as: "identities" , :constraints => { :id => /.*/ }

  # post "ws_register_desligamento", to: "log_desligamento#ws_register_desligamento"
  resources :users , except: :new
  get 'users_perfil', to: "users#show_perfil"
  resources :schedulers
  post "schedulers/:id/run", to: "schedulers#run", as: "scheduler_run"
  resources :producaos , :only => [:index]

  get "painel_producao/:id/(:scope)" , to:"painel_producao#index", as: "painel_producao"

  get "GestaoUsuarios", to: "gestao_usuarios#index", as: "gestao_usuarios", :constraints => { :id => /.*/ }

  get 'GestaoUsuarios/:id/email', to: "gestao_usuarios#email", :constraints => { :id => /.*/ },  :as => :email_gestao_usuario
  post 'GestaoUsuarios/:id/email', to: "gestao_usuarios#enviar_email", :constraints => { :id => /.*/ },  :as => :enviar_email_gestao_usuario

  post "GestaoUsuarios/AlocarEstacao",  to: "gestao_usuarios#alocar_estacao", as: "alocar_estacao"
  get "GestaoUsuarios/EscolherLicencaAlocar",  to: "gestao_usuarios#escolher_licenca_alocar", as: "escolher_licenca_alocar"
  get "GestaoUsuarios/EscolherEstacaoAlocar",  to: "gestao_usuarios#escolher_estacao_alocar", as: "escolher_estacao_alocar"
  get "GestaoUsuarios/:id/confirmardesalocarestacao/:estacao", to: "gestao_usuarios#confirmar_desalocar_estacao", as: "confirmar_desalocar_estacao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermoentrega/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_entrega", as: "imprimir_termo_entrega", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermodevolucao/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_devolucao", as: "imprimir_termo_devolucao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/confirmarremocaolicenca/:licenca", to: "gestao_usuarios#confirmar_remocao_licenca", as: "confirmar_remocao_licenca", :constraints => { :id => /.*/ }
  post "GestaoUsuarios/AlocarLicenca", to: "gestao_usuarios#alocar_licenca", as: "alocar_licenca"
  post "GestaoUsuarios/deletelicenca", to: "gestao_usuarios#remover_licenca", as: "remover_licenca"
  post "GestaoUsuarios/DesalocarEstacao", to: "gestao_usuarios#desalocar_estacao", as: "desalocar_estacao"

  resources :funcionarios , :constraints => { :id => /.*/ }
  get 'equipe/:id', to: "funcionarios#equipe", :constraints => { :id => /.*/ }, as: "equipe"

  get "ajax/cis"
  get "ajax/gestores"

  resources :custom_de_paras
  resources :events, :only => [:index]

  resources :mailings
  get  "mailings/enviar_email", to: "mailings#enviar_email"
  post "mailings/enviar_email_sql", to: "mailings#enviar_email_sql"
  post "mailings/confirma_enviar_email", to: "mailings#confirma_enviar_email"
  post "mailings/confirma_enviar_email_sql", to: "mailings#confirma_enviar_email_sql"

  resources :notes

  resources :status_incidentes

  resources :templates_emails

  resources :sql_templates

  root "cis#index"

  mount Sidekiq::Web, at: '/sidekiq' ,  :constraints => AdminConstraint.new(:manage, :sidekiq)

  resources :ramal, :only => [:index]
 
  resources :audits
  # resources :atributos


  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :cadrelatorios
  match 'cadrelatorios/:id/duplicar', to: "cadrelatorios#duplicar", :as => :duplicar_relatorio, via: [:get, :post]

  resources :statuscis

  match 'relatorio_publico/:id', to: "relatorio#index", as: "relatorio", via: [:get, :post]
  match 'relatorio/:id', to: "relatorio#index_publico", as: "relatorio_publico", via: [:get, :post]
  match 'email/:acao/:id', to: "email#enviar", via: [:get, :post]
  match 'email/enviar_email/:id', to: "email#enviar+email", via: [:get, :post]

  match '/tasks/todos', to: 'tasks#todos', via: [:get, :post]
  match '/cis/todos', to: 'cis#todos', via: [:get, :post]

  match '/tasks/:id/new_from_ci', to: 'tasks#new_from_ci', as: "tasks_new_from_ci", via: [:get, :post]

  resources :parametros #, :only => [:index,:edit,:update,:new]
  match 'parametros/:id/duplicar', to: "parametros#duplicar", :as => :duplicar_parametro, via: [:get, :post]

  resources :dicdados
  match 'dicdados/:id/duplicar', to: "dicdados#duplicar", :as => :duplicar_dicdado, via: [:get, :post]


  get 'cis/:id/email', to: "cis#email",  :as => :email
  post 'cis/:id/email', to: "cis#enviar_email",  :as => :enviar_email  #, defaults: { format: 'js' }
  get "cis/:id/log", to: "cis#log", as: "log_ci"
  post 'cis/:id/log', to: "cis#register_log",  :as => :register_log

  get 'cis/:id/impactados', to: "cis#impactados",  :as => :impactados
  get 'cis/:id/dependentes', to: "cis#dependentes",  :as => :dependentes
  get 'cis/:id/dependentes_all', to: "cis#dependentes_all",  :as => :dependentes_all
  get 'cis/:id/grafico_impactados', to: "cis#grafico_impactados",  :as => :grafico_impactados
  get 'cis/:id/impactados_h', to: "cis#impactados_h", :as => :impactados_h
  get 'cis/:id/dependentes_h', to: "cis#dependentes_h", :as => :dependentes_h
  #get 'cis/:id/abrir_alerta', to: "cis#abrir_alerta", :as => :abrir_alerta

  post 'cis/:id/novo_dependente', to: "cis#gera_novo_dependente", :as => :gera_novo_dependente
  match 'cis/:id/novo_dependente', to: "cis#novo_dependente", :as => :novo_dependente, via: [:get, :post]
  post 'cis/:id/novo_impactado', to: "cis#gera_novo_impactado", :as => :gera_novo_impactado
  match 'cis/:id/novo_impactado', to: "cis#novo_impactado", :as => :novo_impactado, via: [:get, :post]

  post 'cis/:id/elimina_dependente', to: "cis#elimina_dependente", :as => :elimina_dependente
  match 'cis/:id/elimina_dependente', to: "cis#ask_elimina_dependente", :as => :ask_elimina_dependente, via: [:get, :post]
  post 'cis/:id/elimina_impactado', to: "cis#elimina_impactado", :as => :elimina_impactado
  match 'cis/:id/elimina_impactado', to: "cis#ask_elimina_impactado", :as => :ask_elimina_impactado, via: [:get, :post]

  post 'cis/:id/duplicar_ci', to: "cis#duplicar_ci", :as => :duplicar_ci
  match 'cis/:id/duplicar_ci', to: "cis#ask_duplicar_ci", :as => :ask_duplicar_ci, via: [:get, :post]
  

  match 'cis/:id/confirmar_eliminacao', to: "cis#confirmar_eliminacao", :as => :confirmar_eliminacao, via: [:get, :post]
  post 'cis/:id/cis_eliminar', to: "cis#eliminar", :as => :eliminar_ci
  match 'cis/checkChave', to: "cis#check_chave", via: [:get, :post]

  match 'cis/massiveupdate', to: "cis#massiveupdate", via: [:get, :post]

  # get '/cis/:id', to: "cis#show", :constraints => { :id => /.*/ }
  # match '/cis2', to: 'cis#index2'


  # get 'cis/search', to: "cis#search"
  get 'CMDB', to: "cis#index"

  resources :cis
  resources :criticidades

  resources :sites

  resources :tasks

  resources :categories

  resources :authors

  resources :console

  resources :tipocis

  get '/404' => 'errors#not_found'            , :via => :all
  get '/422' => 'errors#server_error'         , :via => :all
  get '/500' => 'errors#internal_server_error', :via => :all

  # get '*a', :to => 'cis#index'


end

app/models/tipoci.rb
# Encoding: utf-8
class Tipoci < ActiveRecord::Base
  attr_accessible :Descricao, :tipo, :Owner, :perfil, :tab
  has_many :dicdados

  default_scope { order('tipo ASC') }
  

  OWNER_SCREEN_SIZE = 20
  OWNER_MAX_LENGTH = 20

  after_save :limpa_cache

  validates :tipo, :presence => {:message => I18n.t("errors.tipoci.tipo.presence") }
  validates :tipo, :uniqueness => {:case_sensitive => false, :message => I18n.t("errors.tipoci.tipo.uniqueness") }
  validates :perfil, :format => { :with => /\A(?:\w+(?:\[(?:view|edit)\]\s*|\s*|$))*\z/, :message => I18n.t("errors.tipoci.perfil.format") }



  #def to_s
  #		puts "#{tipo}:#{Owner}"

  #end

  class Taby
    def initialize(__tab)
      @tab = __tab
    end
    def name
      @tab
    end
    def id
      @tab
    end
  end

  def tabs
    if !self.tab.blank? && self.tab.include?("Caracteristicas")
      arr =  [] 
    else
     arr = [Taby.new("Caracteristicas")]
    end
    # arr = [Taby.new("Caracteristicas")]
    self.tab.split(",").uniq.each { |label| arr << Taby.new(label) } if ! self.tab.nil?
    arr
  end


  def self.esta_em_uso?(id)
    Ci.where(:tipoci_id => id).exists?
  end

  private
  def limpa_cache
    Rails.logger.debug "[DEBUG]Tipoci:after_save: limpando cache ability*"
    Rails.cache.delete_matched("cache:ability*")
  end

end

app/controllers/tipocis_controller.rb
class TipocisController < ApplicationController
  # GET /tipocis
  # GET /tipocis.json
    before_filter :authenticate_user!
  authorize_resource 
  def index
    @tipocis = Tipoci.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @tipocis }
      format.json { render json: @tipocis }
    end
  end

  # GET /tipocis/1
  # GET /tipocis/1.json
  def show
    @tipoci = Tipoci.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipoci }
    end
  end

  # GET /tipocis/new
  # GET /tipocis/new.json
  def new
    @tipoci = Tipoci.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipoci }
    end
  end

  # GET /tipocis/1/edit
  def edit
    @tipoci = Tipoci.find(params[:id])
    @tipoci.tab.gsub!("_"," ") if ! @tipoci.tab.nil?
  end

  # POST /tipocis
  # POST /tipocis.json
  def create
    @tipoci = Tipoci.new(params[:tipoci])



    respond_to do |format|
      if @tipoci.save
        format.html { redirect_to @tipoci, notice: 'Tipo foi criado com sucesso !' }
        format.json { render json: @tipoci, status: :created, location: @tipoci }
      else
        format.html { render action: "new" }
        format.json { render json: @tipoci.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipocis/1
  # PUT /tipocis/1.json
  def update
    @tipoci = Tipoci.find(params[:id])
    puts params[:tipoci][:tab]
    params[:tipoci][:tab].gsub!(" ","_")

    respond_to do |format|
      if @tipoci.update_attributes(params[:tipoci])
        format.html { redirect_to @tipoci, notice: 'Tipo foi atualizado com sucesso !' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipoci.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipocis/1
  # DELETE /tipocis/1.json
  def destroy
    if Tipoci.esta_em_uso?(params[:id])
      flash[:error] = I18n.t("errors.tipoci.tipo_em_uso") #{}"Nao é possivel apagar esse Campo. Existem atributos de Ativos com esse campo"
    else
      @tipoci = Tipoci.find(params[:id])
      @tipoci.destroy
    end

    respond_to do |format|
      format.html { redirect_to tipocis_url,  notice: 'Tipo foi excluido com sucesso !' }
      format.json { head :no_content }
    end
  end
end

app/views/tipocis/_form.html.slim
.container
  .row
    div
      = form_for(@tipoci, :html => {:class => "panel-body #{controller.action_name}_tipoci"}) do |f|
        - if @tipoci.errors.any?
          #error_explanation
            h2
              = pluralize(@tipoci.errors.count, "erro")
              |  ao tentar salvar esse tipo de Ativo
            ul
              - @tipoci.errors.full_messages.each do |msg|
                li
                  = msg
        .form-group
          label[for="tipo"]
            | Tipo do Ativo:
          = f.text_field :tipo, :maxlength=>30,  class: "form-control", autofocus: ""       
        .form-group
          label[for="Descricao"]
            | Descricao:
          = f.text_field :Descricao, :maxlength=>50,  class: "form-control"        
        .form-group
          label[for="Owner"]
            | Owner:
          = f.text_field :Owner, :maxlength=>30,  class: "form-control"        
        .form-group
          label[for="perfil"]
            | Perfis Autorizados:
          = f.text_field :perfil, :maxlength=>200,  class: "form-control" , placeholder: "perfil perfil perfil[view] perfil" 
        .form-group
          label[for="Tabs"]
            | Tabs da tela de Ativo:
          = f.text_field :tab, :maxlength=>200,  class: "form-control", :pattern => "[a-zA-Z0-9\ \_\ç\ã\õ\á\é\ó\í,]*" , placeholder: "nome,nome,nome,nome (sem caracter especiais)" 
        button.btn.btn-primary.btn-md[type="submit"]
          |  Salvar Tipo Ativo
        = link_to 'Cancelar', tipocis_path,  {:id => "Cancelar", :class => "btn btn-danger btn-md margin-left"}

app/views/tipocis/edit.html.erb
<% title "GAM. Editando Tipo Ativo: #{@tipoci.tipo}" %>
<h1>Alterando Tipo Ativo</h1>
<%= render 'form' %>

app/views/tipocis/index.html.erb
<% title "GAM. Tipos Ativo." %>
<!-- <%= csrf_meta_tag %> -->
<script type="text/javascript">
$(document).ready( function(){
    $('#coolTable').DataTable({
      pageLength: 100,
      pagingType: "full_numbers",
      language: { 
          search: "Filtrar:" ,
          infoFiltered: "(Total de _MAX_ registros)",
          info:   "Mostrando do registro _START_ até _END_ de um total de  _TOTAL_ filtrados",
          "lengthMenu":     "Mostrar _MENU_ registros",
          "paginate": {
              "first":      "Primeira",
              "last":       "Última",
              "next":       "Próxima",
              "previous":   "Anterior"
          },
          "infoEmpty":      "Mostrando do registro 0 até 0 de um total de 0 registros",
          "zeroRecords":    "Nenhum registro achado",
          }   

      
    })
});
</script>
</script>
<div id="content">
  <div class="panel panel-default">
    
    <% if (can? :manage, Tipoci) %>
      <div class="panel-heading">
        <%= link_to 'Novo Tipo', new_tipoci_path , class: "btn btn-primary btn-xs" %>
      </div>
    <% end %>
    <div class="panel-body">
      <table  class="generalTable" id="coolTable" >
        <thead>
        <tr class="head">
          <th>Tipo Ativo</th>
          <th>Descricao</th>
          <th>Owner</th>          
          <th>Tabs</th>
          <th>Perfis Autorizados</th>
          <% if (can? :manage, Tipoci)  %>
               <th></th>
          <% end %>
        </tr> 
        </thead>
        <tbody>
        <% @tipocis.each do |tipoci| %>
        <tr>
          <td><%= link_to tipoci.tipo , tipoci_path(tipoci)%></td>
          <td><%= tipoci.Descricao %></td>
          <td><%= tipoci.Owner%></td>
          <td><%= tipoci.tab.gsub("_"," ") if ! tipoci.tab.nil?%></td>

          <td><%= tipoci.perfil%></td>
          <% if (can? :manage, Tipoci)  %>
            <td>
                <%= link_to 'Editar', edit_tipoci_path(tipoci), class: "btn btn-primary btn-xs" %>
                <%= link_to 'Excluir', tipoci, method: :delete,  class: "btn btn-danger btn-xs", data: { confirm: "Voce realmente deseja excluir o tipo de ativo #{tipoci.tipo} ?" } %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
      </table>
      <br />
      <% if (can? :manage, Tipoci) %>
      <div class="panel-heading">
        <%= link_to 'Novo Tipo', new_tipoci_path , class: "btn btn-primary btn-xs" %>
      </div>
    <% end %>
      </div> <!-- panel-body -->
      </div> <!-- panel panel-default -->
      </div> <!-- id="content" -->

app/views/tipocis/new.html.erb
<% title "GAM. Novo Tipo Ativo." %>
<h1>Novo Tipo Ativo</h1>
<%= render 'form' %>

app/views/tipocis/show.html.slim
- title "GAM. Tipo Ativo: #{@tipoci.tipo}"
.container
  .row
    / p#notice
    /   = notice
    .panel.panel-default.panel-primary
      .panel-body.panel-primary
        h4  
           = "Ativo tipo: #{@tipoci.tipo}"
        .list-group
          .list-group-item
            h4.list-group-item-heading
              | Descricao
            p.list-group-item-text
              = @tipoci.Descricao
          .list-group-item
            h4.list-group-item-heading
              | Onwer
            p.list-group-item-text
              = @tipoci.Owner
          .list-group-item
            h4.list-group-item-heading
              | Perfis Autorizados
            p.list-group-item-text
              = @tipoci.perfil
          .list-group-item
            h4.list-group-item-heading
              | Tabs da tela de Ativo
            p.list-group-item-text
              = @tipoci.tab.gsub("_"," ")
          
    - if (can? :manage, Tipoci)
      = link_to 'Editar', edit_tipoci_path(@tipoci), :class => "btn btn-primary btn-md margin-left"
    = link_to 'Listagem', tipocis_path , :class => "btn btn-primary btn-md margin-left"