config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

ItMgmt::Application.routes.draw do


  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}#, path_names: {sign_in: "login", sign_out: "logout"}
  resources :incidentes
  resources :grupos
  # resources :comandos_automacaos
  resources :softwares

  # resources :inventario
  get "/inventario", to: "inventario#index", as: "inventario"
  get "/inventario/:id", to: "inventario#show", as: "get_inventario"
  get "/inventario/:id/:acao", to: "inventario#acao", as: "acao_inventario"
  post "/inventario", to: "inventario#confirma", as: "confirmar_inventario"
  

  
  get "Licencas/PorGestor/:id(/:versao)", to: "licencas#porGestor", as: "LicencasPorGestor" , :constraints => { :id => /[a-zA-z0-9.]*/ }

  get "Licencas/PorUsuario/:id", to: "licencas#porUsuario", as: "LicencasPorUsuario" , :constraints => { :id => /.*/ }


  get "identities/:id", to: "identities#show", as: "identities" , :constraints => { :id => /.*/ }

  # post "ws_register_desligamento", to: "log_desligamento#ws_register_desligamento"
  resources :users , except: :new
  get 'users_perfil', to: "users#show_perfil"
  resources :schedulers
  post "schedulers/:id/run", to: "schedulers#run", as: "scheduler_run"
  resources :producaos , :only => [:index]

  get "painel_producao/:id/(:scope)" , to:"painel_producao#index", as: "painel_producao"

  get "GestaoUsuarios", to: "gestao_usuarios#index", as: "gestao_usuarios", :constraints => { :id => /.*/ }

  get 'GestaoUsuarios/:id/email', to: "gestao_usuarios#email", :constraints => { :id => /.*/ },  :as => :email_gestao_usuario
  post 'GestaoUsuarios/:id/email', to: "gestao_usuarios#enviar_email", :constraints => { :id => /.*/ },  :as => :enviar_email_gestao_usuario

  post "GestaoUsuarios/AlocarEstacao",  to: "gestao_usuarios#alocar_estacao", as: "alocar_estacao"
  get "GestaoUsuarios/EscolherLicencaAlocar",  to: "gestao_usuarios#escolher_licenca_alocar", as: "escolher_licenca_alocar"
  get "GestaoUsuarios/EscolherEstacaoAlocar",  to: "gestao_usuarios#escolher_estacao_alocar", as: "escolher_estacao_alocar"
  get "GestaoUsuarios/:id/confirmardesalocarestacao/:estacao", to: "gestao_usuarios#confirmar_desalocar_estacao", as: "confirmar_desalocar_estacao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermoentrega/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_entrega", as: "imprimir_termo_entrega", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermodevolucao/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_devolucao", as: "imprimir_termo_devolucao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/confirmarremocaolicenca/:licenca", to: "gestao_usuarios#confirmar_remocao_licenca", as: "confirmar_remocao_licenca", :constraints => { :id => /.*/ }
  post "GestaoUsuarios/AlocarLicenca", to: "gestao_usuarios#alocar_licenca", as: "alocar_licenca"
  post "GestaoUsuarios/deletelicenca", to: "gestao_usuarios#remover_licenca", as: "remover_licenca"
  post "GestaoUsuarios/DesalocarEstacao", to: "gestao_usuarios#desalocar_estacao", as: "desalocar_estacao"

  resources :funcionarios , :constraints => { :id => /.*/ }
  get 'equipe/:id', to: "funcionarios#equipe", :constraints => { :id => /.*/ }, as: "equipe"

  get "ajax/cis"
  get "ajax/gestores"

  resources :custom_de_paras
  resources :events, :only => [:index]

  resources :mailings
  get  "mailings/enviar_email", to: "mailings#enviar_email"
  post "mailings/enviar_email_sql", to: "mailings#enviar_email_sql"
  post "mailings/confirma_enviar_email", to: "mailings#confirma_enviar_email"
  post "mailings/confirma_enviar_email_sql", to: "mailings#confirma_enviar_email_sql"

  resources :notes

  resources :status_incidentes

  resources :templates_emails

  resources :sql_templates

  root "cis#index"

  mount Sidekiq::Web, at: '/sidekiq' ,  :constraints => AdminConstraint.new(:manage, :sidekiq)

  resources :ramal, :only => [:index]
 
  resources :audits
  # resources :atributos


  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :cadrelatorios
  match 'cadrelatorios/:id/duplicar', to: "cadrelatorios#duplicar", :as => :duplicar_relatorio, via: [:get, :post]

  resources :statuscis

  match 'relatorio_publico/:id', to: "relatorio#index", as: "relatorio", via: [:get, :post]
  match 'relatorio/:id', to: "relatorio#index_publico", as: "relatorio_publico", via: [:get, :post]
  match 'email/:acao/:id', to: "email#enviar", via: [:get, :post]
  match 'email/enviar_email/:id', to: "email#enviar+email", via: [:get, :post]

  match '/tasks/todos', to: 'tasks#todos', via: [:get, :post]
  match '/cis/todos', to: 'cis#todos', via: [:get, :post]

  match '/tasks/:id/new_from_ci', to: 'tasks#new_from_ci', as: "tasks_new_from_ci", via: [:get, :post]

  resources :parametros #, :only => [:index,:edit,:update,:new]
  match 'parametros/:id/duplicar', to: "parametros#duplicar", :as => :duplicar_parametro, via: [:get, :post]

  resources :dicdados
  match 'dicdados/:id/duplicar', to: "dicdados#duplicar", :as => :duplicar_dicdado, via: [:get, :post]


  get 'cis/:id/email', to: "cis#email",  :as => :email
  post 'cis/:id/email', to: "cis#enviar_email",  :as => :enviar_email  #, defaults: { format: 'js' }
  get "cis/:id/log", to: "cis#log", as: "log_ci"
  post 'cis/:id/log', to: "cis#register_log",  :as => :register_log

  get 'cis/:id/impactados', to: "cis#impactados",  :as => :impactados
  get 'cis/:id/dependentes', to: "cis#dependentes",  :as => :dependentes
  get 'cis/:id/dependentes_all', to: "cis#dependentes_all",  :as => :dependentes_all
  get 'cis/:id/grafico_impactados', to: "cis#grafico_impactados",  :as => :grafico_impactados
  get 'cis/:id/impactados_h', to: "cis#impactados_h", :as => :impactados_h
  get 'cis/:id/dependentes_h', to: "cis#dependentes_h", :as => :dependentes_h
  #get 'cis/:id/abrir_alerta', to: "cis#abrir_alerta", :as => :abrir_alerta

  post 'cis/:id/novo_dependente', to: "cis#gera_novo_dependente", :as => :gera_novo_dependente
  match 'cis/:id/novo_dependente', to: "cis#novo_dependente", :as => :novo_dependente, via: [:get, :post]
  post 'cis/:id/novo_impactado', to: "cis#gera_novo_impactado", :as => :gera_novo_impactado
  match 'cis/:id/novo_impactado', to: "cis#novo_impactado", :as => :novo_impactado, via: [:get, :post]

  post 'cis/:id/elimina_dependente', to: "cis#elimina_dependente", :as => :elimina_dependente
  match 'cis/:id/elimina_dependente', to: "cis#ask_elimina_dependente", :as => :ask_elimina_dependente, via: [:get, :post]
  post 'cis/:id/elimina_impactado', to: "cis#elimina_impactado", :as => :elimina_impactado
  match 'cis/:id/elimina_impactado', to: "cis#ask_elimina_impactado", :as => :ask_elimina_impactado, via: [:get, :post]

  post 'cis/:id/duplicar_ci', to: "cis#duplicar_ci", :as => :duplicar_ci
  match 'cis/:id/duplicar_ci', to: "cis#ask_duplicar_ci", :as => :ask_duplicar_ci, via: [:get, :post]
  

  match 'cis/:id/confirmar_eliminacao', to: "cis#confirmar_eliminacao", :as => :confirmar_eliminacao, via: [:get, :post]
  post 'cis/:id/cis_eliminar', to: "cis#eliminar", :as => :eliminar_ci
  match 'cis/checkChave', to: "cis#check_chave", via: [:get, :post]

  match 'cis/massiveupdate', to: "cis#massiveupdate", via: [:get, :post]

  # get '/cis/:id', to: "cis#show", :constraints => { :id => /.*/ }
  # match '/cis2', to: 'cis#index2'


  # get 'cis/search', to: "cis#search"
  get 'CMDB', to: "cis#index"

  resources :cis
  resources :criticidades

  resources :sites

  resources :tasks

  resources :categories

  resources :authors

  resources :console

  resources :tipocis

  get '/404' => 'errors#not_found'            , :via => :all
  get '/422' => 'errors#server_error'         , :via => :all
  get '/500' => 'errors#internal_server_error', :via => :all

  # get '*a', :to => 'cis#index'


end

app/models/dicdado.rb
class Dicdado < ActiveRecord::Base
  belongs_to :tipoci

  attr_accessible :nome, :ordem, :url, :tipoci_id, :descricao ,:valores ,:apelido  ,:tipo , :regex, :mandatorio  ,:tooltip     ,:comentarios, :tab, :bloqueado

  default_scope { order('tipoci_id ASC, ordem ASC') }

  validates :nome, :presence => {                          :message => I18n.t("errors.dicdado.nome.presence") }
  validates :tipoci_id, :presence => {                     :message => " eh mandatorio" }
  validates :apelido, :presence => {                       :message => I18n.t("errors.dicdado.apelido.presence") }
  validates :apelido, :format => { :with => /\A[a-zA-Z0-9]+\z/, :message => I18n.t("errors.dicdado.apelido.format") }
  validates :nome, uniqueness: { scope: [:tipoci_id] , :message => I18n.t("errors.dicdado.nome.uniqueness") }


  self.per_page = 20

  after_save ThinkingSphinx::RealTime.callback_for(:dicdado)

  def nice_tipoci
    tipoci.nil? ? "" : tipoci.tipo
  end

end

app/controllers/dicdados_controller.rb
class DicdadosController < ApplicationController
  # GET /dicdados
  # GET /dicdados.xml
  authorize_resource
    before_filter :authenticate_user!
  

  def carrega_agregadas
    @tipocis = Tipoci.all
    @tabs = @tipocis.map { |x| [x.id,x.tipo] }
    # @tabs.each do |x|
    #   x[2] = "" if x[2].nil?
    #   x[2] = x[2].split(",")
    # end
    # @tabs.map!{ |x| x[2] = "" if x[2].nil?}
  end

  def index

    @search = params[:search] || session[:search_dicdados]
    session[:search_dicdados] = @search

    
    begin
      @dicdados = Dicdado.search @search, :match_mode => :boolean, :per_page => 15 , :page => params[:page], :sort_mode => :extended , :order => "sort_tipoci_id ASC, sort_ordem ASC"
      @dicdados.compact!
    rescue 
      flash[:error] = "Error[DB0001] - Search Engine com Problema"
      @dicdados = Dicdado.paginate(:page => params[:page])
    end

    
    session[:search_dicdados_tipoci] = @dicdados[0].tipoci_id unless @dicdados[0].nil?

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dicdados }
    end
  end

  # GET /dicdados/1
  # GET /dicdados/1.xml
  def show
    @dicdado = Dicdado.find(params[:id])
    carrega_agregadas

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dicdado }
    end
  end

  # GET /dicdados/new
  # GET /dicdados/new.xml
  def new
    @dicdado = Dicdado.new
    @dicdado.tipoci_id = session[:search_dicdados_tipoci] unless session[:search_dicdados_tipoci].nil?
    carrega_agregadas


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dicdado }
    end
  end

  # GET /dicdados/1/edit
  def edit
    @dicdado = Dicdado.find(params[:id])
    carrega_agregadas
  end


  def duplicar
    begin
      dicdado_orig = Dicdado.find(params[:id])
      @dicdado = dicdado_orig.deep_clone
      carrega_agregadas
      respond_to do |format|
        format.html { render :action => 'new' }
      end
    rescue Exception => error
      puts error
      puts error.backtrace
      flash[:error] = "Error[DD0001] - Dicionario de ativos #{[params[:id]]} Invalido"
      redirect_to "/dicdados" and return
    end
  end

  # POST /dicdados
  # POST /dicdados.xml
  def create
    @dicdado = Dicdado.new(params[:dicdado])
    carrega_agregadas
    session[:search_dicdados_tipoci] = @dicdado.tipoci_id unless @dicdado.nil?

    respond_to do |format|
      if @dicdado.save
        format.html { redirect_to(@dicdado, :notice => 'Campo foi criado com sucesso !') }
        format.xml  { render :xml => @dicdado, :status => :created, :location => @dicdado }
      else
        carrega_agregadas
        format.html { render :action => "new" }
        format.xml  { render :xml => @dicdado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dicdados/1
  # PUT /dicdados/1.xml
  def update
    @dicdado = Dicdado.find(params[:id])
    carrega_agregadas

    respond_to do |format|
      if @dicdado.update_attributes(params[:dicdado])
        format.html { redirect_to(@dicdado, :notice => 'Campo foi atualizado com sucesso !') }
        format.xml  { head :ok }
      else
        carrega_agregadas
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dicdado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dicdados/1
  # DELETE /dicdados/1.xml
  def destroy
    if Atributo.esta_em_uso?(params[:id]) then
      flash[:error] = "Nao é possivel apagar esse Campo. Existem atributos de Ativos com esse campo"

    else
      @dicdado = Dicdado.find(params[:id])
      @dicdado.destroy
    end
    respond_to do |format|
      format.html { redirect_to(dicdados_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dicdados_helper.rb
module DicdadosHelper
end

app/views/dicdados/_form.html.erb
<%= form_for(@dicdado) do |f| %>
<% if @dicdado.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@dicdado.errors.count, "erro") %> ao salvar esse campo de um ativo</h2>

  <ul>
    <% @dicdado.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<label>Tipo de Ativo
</label>
<%= f.select :tipoci_id, @tipocis.collect { |c| [ c.tipo, c.id ] } %>

<div class="spacer"></div>


<label>Nome do Campo
<span class="small">Titulo do campo na tela de Ativo</span>
</label>
<%= f.text_field :nome %>

<div class="spacer"></div>


<label>Descricao
<span class="small">Subtitulo da tela de edição </span>
</label>
<%= f.text_field :descricao %>
<div class="spacer"></div>


<label>Apelido
<span class="small">Somente caracteres - a ser usado em emails </span>
</label>
<%= f.text_field :apelido%>
<div class="spacer"></div>




<label>Valores padrao (combobox):
<span class="small">Opcional</span>
</label>
<%= f.text_area :valores, :size => "150x6" %>
<div class="spacer"></div>


<label>Ordem de Apresentacao:
<span class="small">Na tela de Ativos </span>
</label>

<%= f.text_field :ordem %>
<div class="spacer"></div>


<label>Regex
<span class="small">Opcional</span>
</label>
<%= f.text_field :regex, :size=>100 %>
<div class="spacer"></div>


<label>Campo é mandatório
</label>
<%= f.check_box :mandatorio %>
<div class="spacer"></div>


<label>URL
<span class="small">Opcional </span>
</label>
<%= f.text_field :url, :size=>100 %>
<div class="spacer"></div>


<label>Dica de Ajuda
<span class="small">Tooltip na tela de edição </span>
</label>
<br>
<%= f.text_area :tooltip, :size => "150x6" %>
<div class="spacer"></div>


<label>Comentarios
<span class="small">Usado internamente</span>
</label>
<br>
<%= f.text_area :comentarios, :size => "150x6" %>
<div class="spacer"></div>


<div class="actions">

    <button type="submit" id="SalvarCampoAtivo">Salvar Campo do Ativo</button>
<div class="spacer"></div>


<% end %>

app/views/dicdados/_form.html.slim
= javascript_include_tag "tab_dicdados.js"
.container
  .row
    div
      = form_for(@dicdado, :html => {:class => "panel-body #{controller.action_name}_user"}) do |f|
        - if @dicdado.errors.any?
          #error_explanation
            h2
              = pluralize(@dicdado.errors.count, "erro")
              |  ao tentar salvar esse Campo:
            ul
              - @dicdado.errors.full_messages.each do |msg|
                li
                  = msg
        .form-group
          label[for="tipoci_id"]
            | Tipo do Ativo:  
          = f.select :tipoci_id, @tabs.collect { |c| [ c[1],c[0] ] }, {},  { class: "form-control" , autofocus: ""}
        
        .form-group  
          label[for="tab"]
            | Tab
          = f.grouped_collection_select :tab, Tipoci.order(:tipo), :tabs, :tipo, :id, :name, {include_blank: true} ,  { class: "form-control"}
        .form-group
          label[for="nome"]
            | Nome:
          = f.text_field :nome, :maxlength=>50, class: "form-control", placeholder: "Nome do campo a ser vizualizado na tela de ativos"
        .form-group
          label[for="descricao"]
            | PlaceHolder:
          = f.text_field :descricao, :maxlength=>50,placeholder: "placeholder a ser mostrado nos campos da tela de edição de ativos",  class: "form-control"
        .form-group
          label[for="apelido"]
            | Apelido:
          = f.text_field :apelido, :maxlength=>50,placeholder: "Apelido interno para parametrizacao",  class: "form-control"
        .form-group
          label[for="valores"]
            | Valores Possiveis:
          = f.text_area :valores, :size => "150x6", placeholder: "Opcional: Valores possiveis para dropbox separados por ,",  class: "form-control"
        .form-group
          label[for="ordem"]
            | Ordem de Apresentacao na tela de ativos:
          = f.text_field :ordem, :maxlength=>6, placeholder: "Ordem de apresentacao na tela de ativos",  class: "form-control"
        .form-group
          label[for="regex"]
            | Expressao Regular:
          = f.text_field :regex, :maxlength=>200, placeholder: "Opcional: regex para validacao do campo",  class: "form-control"
        .form-group
          label[for="mandatorio"]
            | Campo é mandatório ?
          = f.check_box :mandatorio, class: "itam_checkbox_margin-left"
        .form-group
          label[for="bloqueado"]
            | Campo é bloqueado para edição ?
          = f.check_box :bloqueado, class: "itam_checkbox_margin-left"
        .form-group
          label[for="url"]
            | URL:
          = f.text_field :url, :maxlength=>100, placeholder: "Opcional: URL",  class: "form-control"
        .form-group
          label[for="comentarios"]
            | Comentarios:
          = f.text_area :comentarios, :size => "150x6", placeholder: "Opcional: Comentarios internos",  class: "form-control"
        button.btn.btn-primary.btn-md[type="submit"]
          |  Salvar Campo 
        = link_to 'Cancelar', dicdados_path,  {:id => "Cancelar", :class => "btn btn-danger btn-md margin-left"}

app/views/dicdados/edit.html.erb
<% title "GAM. Campo: #{@dicdado.nome}" %>
<h1>Alterando Campo de um Ativo</h1>

<%= render 'form' %>

app/views/dicdados/index.html.erb
<% title "GAM: Dicionario de Dados" %>
<div class="panel panel-default">

  <% [:info, :error].each do |key| %>
     <% if flash[key] %>
     <div class="flash <%= key %>" id="flash">
       <%= flash[key] %>
     </div>
     <% end %>
  <% end %>


  <!-- <div class="panel-heading"><h1>Dicionario de Dados - Campos dos Ativos</h1></div> -->

  <%= form_tag(dicdados_path, :method => "get", :class => "panel-body") do %>
  <%= text_field_tag(:search, @search, :size => 50, :autofocus => true) %>
  <%= button_tag(type: "submit", class: "btn btn-primary btn-xs") { "Filtrar" }%>
  <%= link_to 'Novo Campo', new_dicdado_path, class: "btn btn-primary btn-xs" if (can? :manage, Dicdado) %>
  <% end %> <!-- form -->



  <div class="panel-body">
    <table  class="generalTable">
      <thead>
        <tr class="head">
          <th>Tipo CI</th>
          <th>Campo</th>
          <th>Apelido</th>
          <th>Regex</th>
          <th>Mandatorio</th>
          <th>Tab</th>
          <th>Ordem</th>
          <% if (can? :manage, Dicdado)  %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @dicdados.each do |dicdado| %>
          <tr>
            <td><%= link_to dicdado.nice_tipoci, dicdado %></td>
            <td><%= link_to dicdado.nome, dicdado %></td>
            <td><%= dicdado.apelido %></th>
            <td><%= dicdado.regex %></th>  
            <td><%= dicdado.mandatorio ? "Sim" : "" %></td>   
            <td><%= dicdado.tab %></td>
            <td><%= dicdado.ordem %></td>
            <% if (can? :manage, Dicdado)  %>
              <td>
                  <%= link_to 'Editar', edit_dicdado_path(dicdado), class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Duplicar', duplicar_dicdado_path(dicdado), class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Excluir', dicdado, data: { confirm: "Voce realmente deseja excluir o campo '#{dicdado.nome}'' do tipo '#{dicdado.nice_tipoci}'  ?"} , :method => :delete, class: "btn btn-danger btn-xs" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br/>

    <%= will_paginate(@dicdados) %>

  </div> <!-- class panel-body -->
</div> <!-- panel panel-default -->

app/views/dicdados/new.html.erb
<% title "GAM. Novo Campo" %>
<h1>Novo Campo de um Ativo</h1>

<%= render 'form' %>

app/views/dicdados/show.html.slim
- title "GAM. Campo: #{@dicdado.nome}" 
.container
  .row
    p#notice
      = notice
    .panel.panel-default.panel-primary
      .panel-body.panel-primary
        h4  
           = "Campo: #{@dicdado.nome}"
        .list-group
          .list-group-item
            h4.list-group-item-heading
              | Tipo do Ativo
            p.list-group-item-text
              = @dicdado.nice_tipoci
          .list-group-item
            h4.list-group-item-heading
              | Tab de Apresentacao
            p.list-group-item-text
              = @dicdado.tab
          .list-group-item
            h4.list-group-item-heading
              | Apelido
            p.list-group-item-text
              = @dicdado.apelido
          .list-group-item
            h4.list-group-item-heading
              | Descricao/Placeholder
            p.list-group-item-text
              = @dicdado.descricao
          .list-group-item
            h4.list-group-item-heading
              | Valores
            p.list-group-item-text
              = @dicdado.valores
          .list-group-item
            h4.list-group-item-heading
              | Ordem de Apresentacao
            p.list-group-item-text
              = @dicdado.ordem         
          .list-group-item
            h4.list-group-item-heading
              | Tab do formulario de ativos
            p.list-group-item-text
              = @dicdado.tab
          .list-group-item
            h4.list-group-item-heading
              | Expressao Regular
            p.list-group-item-text
              = @dicdado.regex
          .list-group-item
            h4.list-group-item-heading
              | Campo Mandatorio ? 
            p.list-group-item-text
              = @dicdado.mandatorio ? "Sim" : "Nao"           
          .list-group-item
            h4.list-group-item-heading
              | Campo Bloqueado para edição ? 
            p.list-group-item-text
              = @dicdado.bloqueado ? "Sim" : "Nao"           
          .list-group-item
            h4.list-group-item-heading
              | URL  
            p.list-group-item-text
              = @dicdado.url          
          .list-group-item
            h4.list-group-item-heading
              | Comentarios  
            p.list-group-item-text
              = @dicdado.comentarios
    - if (can? :manage, Dicdado)
      = link_to 'Editar', edit_dicdado_path(@dicdado), :class => "btn btn-primary btn-md margin-left"
      = link_to 'Novo Campo', new_dicdado_path, class: "btn btn-primary btn-md margin-left" 
      = link_to 'Duplicar', duplicar_dicdado_path(@dicdado), class: "btn btn-primary btn-md margin-left" 
    = link_to 'Listagem', dicdados_path , :class => "btn btn-primary btn-md margin-left"



/     <tr><td>Tipo de Ativo:</td><td><b><%= @dicdado.nice_tipoci %></b></td></tr>
/ <tr><td>Campo:</td><td><b> <%= @dicdado.nome %></b></td></tr>
/ <tr><td>Apelido:</td><td><b><%= @dicdado.apelido %></b></td></tr>
/ <tr><td>Descricao:</td><td><b><%= @dicdado.descricao %></b></td></tr>
/ <tr><td>Valores:</td><td><b><%= @dicdado.valores %></b></td></tr>
/ <tr><td>Ordem de Apresentacao</td><td><b><%= @dicdado.ordem %></b></td></tr>
/ <tr><td>regex:</td><td><b><%= @dicdado.regex %></b></td></tr>
/ <tr><td>É Mandatorio:</td><td><b><%= @dicdado.mandatorio ? "Sim" : "Nao" %></b></td></tr>
/ <tr><td>URL:</td><td><b><%= @dicdado.url %></b></td></tr>
/ <tr><td>Ajuda:</td><td><b><%= @dicdado.tooltip %></b></td></tr>
/ <tr><td>Comentario Interno:</td><td><b><%= @dicdado.comentarios %></b></td></tr>
/ </table>