config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

ItMgmt::Application.routes.draw do


  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}#, path_names: {sign_in: "login", sign_out: "logout"}
  resources :incidentes
  resources :grupos
  # resources :comandos_automacaos
  resources :softwares

  # resources :inventario
  get "/inventario", to: "inventario#index", as: "inventario"
  get "/inventario/:id", to: "inventario#show", as: "get_inventario"
  get "/inventario/:id/:acao", to: "inventario#acao", as: "acao_inventario"
  post "/inventario", to: "inventario#confirma", as: "confirmar_inventario"
  

  
  get "Licencas/PorGestor/:id(/:versao)", to: "licencas#porGestor", as: "LicencasPorGestor" , :constraints => { :id => /[a-zA-z0-9.]*/ }

  get "Licencas/PorUsuario/:id", to: "licencas#porUsuario", as: "LicencasPorUsuario" , :constraints => { :id => /.*/ }


  get "identities/:id", to: "identities#show", as: "identities" , :constraints => { :id => /.*/ }

  # post "ws_register_desligamento", to: "log_desligamento#ws_register_desligamento"
  resources :users , except: :new
  get 'users_perfil', to: "users#show_perfil"
  resources :schedulers
  post "schedulers/:id/run", to: "schedulers#run", as: "scheduler_run"
  resources :producaos , :only => [:index]

  get "painel_producao/:id/(:scope)" , to:"painel_producao#index", as: "painel_producao"

  get "GestaoUsuarios", to: "gestao_usuarios#index", as: "gestao_usuarios", :constraints => { :id => /.*/ }

  get 'GestaoUsuarios/:id/email', to: "gestao_usuarios#email", :constraints => { :id => /.*/ },  :as => :email_gestao_usuario
  post 'GestaoUsuarios/:id/email', to: "gestao_usuarios#enviar_email", :constraints => { :id => /.*/ },  :as => :enviar_email_gestao_usuario

  post "GestaoUsuarios/AlocarEstacao",  to: "gestao_usuarios#alocar_estacao", as: "alocar_estacao"
  get "GestaoUsuarios/EscolherLicencaAlocar",  to: "gestao_usuarios#escolher_licenca_alocar", as: "escolher_licenca_alocar"
  get "GestaoUsuarios/EscolherEstacaoAlocar",  to: "gestao_usuarios#escolher_estacao_alocar", as: "escolher_estacao_alocar"
  get "GestaoUsuarios/:id/confirmardesalocarestacao/:estacao", to: "gestao_usuarios#confirmar_desalocar_estacao", as: "confirmar_desalocar_estacao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermoentrega/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_entrega", as: "imprimir_termo_entrega", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/imprimirtermodevolucao/:tipo/:ativo", to: "gestao_usuarios#imprimir_termo_devolucao", as: "imprimir_termo_devolucao", :constraints => { :id => /.*/ }
  get "GestaoUsuarios/:id/confirmarremocaolicenca/:licenca", to: "gestao_usuarios#confirmar_remocao_licenca", as: "confirmar_remocao_licenca", :constraints => { :id => /.*/ }
  post "GestaoUsuarios/AlocarLicenca", to: "gestao_usuarios#alocar_licenca", as: "alocar_licenca"
  post "GestaoUsuarios/deletelicenca", to: "gestao_usuarios#remover_licenca", as: "remover_licenca"
  post "GestaoUsuarios/DesalocarEstacao", to: "gestao_usuarios#desalocar_estacao", as: "desalocar_estacao"

  resources :funcionarios , :constraints => { :id => /.*/ }
  get 'equipe/:id', to: "funcionarios#equipe", :constraints => { :id => /.*/ }, as: "equipe"

  get "ajax/cis"
  get "ajax/gestores"

  resources :custom_de_paras
  resources :events, :only => [:index]

  resources :mailings
  get  "mailings/enviar_email", to: "mailings#enviar_email"
  post "mailings/enviar_email_sql", to: "mailings#enviar_email_sql"
  post "mailings/confirma_enviar_email", to: "mailings#confirma_enviar_email"
  post "mailings/confirma_enviar_email_sql", to: "mailings#confirma_enviar_email_sql"

  resources :notes

  resources :status_incidentes

  resources :templates_emails

  resources :sql_templates

  root "cis#index"

  mount Sidekiq::Web, at: '/sidekiq' ,  :constraints => AdminConstraint.new(:manage, :sidekiq)

  resources :ramal, :only => [:index]
 
  resources :audits
  # resources :atributos


  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :cadrelatorios
  match 'cadrelatorios/:id/duplicar', to: "cadrelatorios#duplicar", :as => :duplicar_relatorio, via: [:get, :post]

  resources :statuscis

  match 'relatorio_publico/:id', to: "relatorio#index", as: "relatorio", via: [:get, :post]
  match 'relatorio/:id', to: "relatorio#index_publico", as: "relatorio_publico", via: [:get, :post]
  match 'email/:acao/:id', to: "email#enviar", via: [:get, :post]
  match 'email/enviar_email/:id', to: "email#enviar+email", via: [:get, :post]

  match '/tasks/todos', to: 'tasks#todos', via: [:get, :post]
  match '/cis/todos', to: 'cis#todos', via: [:get, :post]

  match '/tasks/:id/new_from_ci', to: 'tasks#new_from_ci', as: "tasks_new_from_ci", via: [:get, :post]

  resources :parametros #, :only => [:index,:edit,:update,:new]
  match 'parametros/:id/duplicar', to: "parametros#duplicar", :as => :duplicar_parametro, via: [:get, :post]

  resources :dicdados
  match 'dicdados/:id/duplicar', to: "dicdados#duplicar", :as => :duplicar_dicdado, via: [:get, :post]


  get 'cis/:id/email', to: "cis#email",  :as => :email
  post 'cis/:id/email', to: "cis#enviar_email",  :as => :enviar_email  #, defaults: { format: 'js' }
  get "cis/:id/log", to: "cis#log", as: "log_ci"
  post 'cis/:id/log', to: "cis#register_log",  :as => :register_log

  get 'cis/:id/impactados', to: "cis#impactados",  :as => :impactados
  get 'cis/:id/dependentes', to: "cis#dependentes",  :as => :dependentes
  get 'cis/:id/dependentes_all', to: "cis#dependentes_all",  :as => :dependentes_all
  get 'cis/:id/grafico_impactados', to: "cis#grafico_impactados",  :as => :grafico_impactados
  get 'cis/:id/impactados_h', to: "cis#impactados_h", :as => :impactados_h
  get 'cis/:id/dependentes_h', to: "cis#dependentes_h", :as => :dependentes_h
  #get 'cis/:id/abrir_alerta', to: "cis#abrir_alerta", :as => :abrir_alerta

  post 'cis/:id/novo_dependente', to: "cis#gera_novo_dependente", :as => :gera_novo_dependente
  match 'cis/:id/novo_dependente', to: "cis#novo_dependente", :as => :novo_dependente, via: [:get, :post]
  post 'cis/:id/novo_impactado', to: "cis#gera_novo_impactado", :as => :gera_novo_impactado
  match 'cis/:id/novo_impactado', to: "cis#novo_impactado", :as => :novo_impactado, via: [:get, :post]

  post 'cis/:id/elimina_dependente', to: "cis#elimina_dependente", :as => :elimina_dependente
  match 'cis/:id/elimina_dependente', to: "cis#ask_elimina_dependente", :as => :ask_elimina_dependente, via: [:get, :post]
  post 'cis/:id/elimina_impactado', to: "cis#elimina_impactado", :as => :elimina_impactado
  match 'cis/:id/elimina_impactado', to: "cis#ask_elimina_impactado", :as => :ask_elimina_impactado, via: [:get, :post]

  post 'cis/:id/duplicar_ci', to: "cis#duplicar_ci", :as => :duplicar_ci
  match 'cis/:id/duplicar_ci', to: "cis#ask_duplicar_ci", :as => :ask_duplicar_ci, via: [:get, :post]
  

  match 'cis/:id/confirmar_eliminacao', to: "cis#confirmar_eliminacao", :as => :confirmar_eliminacao, via: [:get, :post]
  post 'cis/:id/cis_eliminar', to: "cis#eliminar", :as => :eliminar_ci
  match 'cis/checkChave', to: "cis#check_chave", via: [:get, :post]

  match 'cis/massiveupdate', to: "cis#massiveupdate", via: [:get, :post]

  # get '/cis/:id', to: "cis#show", :constraints => { :id => /.*/ }
  # match '/cis2', to: 'cis#index2'


  # get 'cis/search', to: "cis#search"
  get 'CMDB', to: "cis#index"

  resources :cis
  resources :criticidades

  resources :sites

  resources :tasks

  resources :categories

  resources :authors

  resources :console

  resources :tipocis

  get '/404' => 'errors#not_found'            , :via => :all
  get '/422' => 'errors#server_error'         , :via => :all
  get '/500' => 'errors#internal_server_error', :via => :all

  # get '*a', :to => 'cis#index'


end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  self.primary_key = "Login"
  attr_accessible  :Login,  :NumMatrProfissional,:NomProfissional,:DtaAdmissao,:DtaDemissao,:NomEmailBRQ,:IdtCPF,:IdtRG,:IdtCodigoCentroCusto,:NomCentroCusto,:NomTipoCentroCusto,:IdtCodigoSecao,:NomLocalTrabalho,:NomCidadeLocalTrabalho, :IdtCentroCustoTorre,:DscCentroCustoTorre, :NomAlocacao, :IdLocalTrabalho, :cipa, :semEstacao, :observacao, :brigadista, :afastado,
    :DtaRemocaoAcesso, :FlgIndicaRetorno, :NomGestorProfissional, :NomEmailGestorProfissional, :NomEstadoLocalTrabalho,
    :ramalSendoExterno, :customExternoComOffice365, :justificativaExtComOffice365, :justificativaLoginBloqueado, :loginBloqueado


  alias_attribute :CCTorre ,      :IdtCentroCustoTorre
  alias_attribute :CPF,       :IdtCPF
  alias_attribute :CodigoCC,      :IdtCodigoCentroCusto
  alias_attribute :CodigoSecao,     :IdtCodigoSecao
  alias_attribute :DataAdmissao,  :DtaAdmissao
  alias_attribute :DataDemissao,  :DtaDemissao
  alias_attribute :DataRemocaoAcesso,  :DtaRemocaoAcesso
  alias_attribute :DescCCTorre,     :DscCentroCustoTorre
  alias_attribute :Email,     :NomEmailBRQ
  alias_attribute :LoginGestor,     :NomEmailGestorProfissional
  alias_attribute :NomeGestor,      :NomGestorProfissional
  alias_attribute :Identidade,    :IdtRG
  alias_attribute :Matricula,     :NumMatrProfissional
  alias_attribute :Nome,        :NomProfissional
  alias_attribute :NomeCC,      :NomCentroCusto
  alias_attribute :NomeCidadeTrabalho,:NomCidadeLocalTrabalho
  alias_attribute :NomeLocalTrabalho,:NomLocalTrabalho
  alias_attribute :NomeTipoCC,      :NomTipoCentroCusto
  # alias_attribute :gestor,      :NomEmailGestorProfissional

  @@funcionarios  = nil

  def status
    status_func = ""
    status_func << "Afastado - " if self.afastado
    status_func << "Sem Estacao - " if self.semEstacao
    status_func << (self.observacao || "" ) if  self.semEstacao || self.afastado
    status_func
  end

  def demitido?
    ! self.DataRemocaoAcesso.nil? and self.DataRemocaoAcesso < DateTime.now
  end

  @@funcionarios = nil

  def gestor
    self.NomEmailGestorProfissional.gsub(CONFIG["mail"]["domain"],"")
  end

  def self._all
    if not @@funcionarios
      @@funcionarios = {}
      Funcionario.where(DtaDemissao: nil).each { |f| @@funcionarios[f.Login] = f}
    end
    @@funcionarios
  end

  def self.invalidate
    @@funcionarios = nil
  end


  # colocar navegacao sem precisar ir no bd. 
  # self
  # e gestores chama com (login)

  def self.gestores (login)
    f = Funcionario._all
    gestores = []
    gestor = login
    fim = false
    while not fim
      gestores << [gestor,f[gestor].NomProfissional, "#{f[gestor].NomeTipoCC}/#{f[gestor].DescCCTorre}", f[gestor].ramal]
      gestor = f[gestor].NomEmailGestorProfissional
      fim = gestor =="benjamin" || gestor.nil?
    end
    gestores << [gestor,f[gestor].NomProfissional]
    gestores
  end

  def gestores
    Funcionario.gestores(self.Login)

  end

  def self.funcionarios(login)
    f = Funcionario._all
    funcionarios = []
    f.each { |k,v| funcionarios << [v.Login,v.NomProfissional,v.ramal] if v.NomEmailGestorProfissional == login }
    funcionarios
  end

  def funcionarios
    Funcionario.funcionarios(self.Login)
  end


end

app/controllers/funcionarios_controller.rb
class FuncionariosController  < InheritedResources::Base
  # actions :index, :edit
  load_and_authorize_resource
  before_filter :authenticate_user!

  def load_custom_attributes
    puts "FuncionariosController::load_custom_attributes"
    @attrs = []
    begin
      @funcionario = Funcionario.find(params[:id])
      @funcionario.attribute_names.each do |attr|
        @attrs << [attr,"#{$1}".underscore.humanize,@funcionario.attributes[attr]] if attr =~ /^custom(\w+)$/
      end
    rescue => error
      puts error.backtrace
      flash[:error] = "Error[DB0002] - Funcionario nao encontrado"
    end
    puts "Func: ==> #{@funcionario}"
  end

  def index
    puts "FuncionariosController::index"
    @funcionarios = Funcionario.paginate(:page => params[:page])

  end

  def edit
    load_custom_attributes

  end

  def show
    puts "FuncionariosController::Show"

    load_custom_attributes
  end

  def equipe
    puts "FuncionariosController::equipe"
    f = Funcionario.find_by_Login(params[:id])
    @funcionario = f
    @gestores = f.gestores
    @equipe = f.funcionarios
    @logins = f.funcionarios.map{ |x| x[0]}.join(",")

  end

end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "erro") %> ao tentar salver os atributos do funcionario </h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<label>Cipa ?
<span class="small">Integrante da Cipa? </span>
</label>
<div class="field">
    <%= f.check_box :cipa %>
</div>

<div class="spacer"></div>


<label>Brigadista ?
<span class="small">É brigadista? </span>
</label>
<div class="field">
    <%= f.check_box :brigadista %>
</div>

<div class="spacer"></div>

<label>Sem Estacao ?
<span class="small">Esse usuario nao usa estação da Empresa? </span>
</label>
<div class="field">
    <%= f.check_box :semEstacao %>
</div>


<div class="spacer"></div>

<label>É externo e possui ramal ?

</label>
<div class="field">
    <%= f.check_box :ramalSendoExterno %>
</div>

<div class="spacer"></div>


<% @attrs.each do |attr| %>
  <label><%= attr[1] %>?
  </label>
  <div class="field">
<!--    <input name="funcionario[<%= attr[0]%>]" type="hidden" value="0" />   
   <input id="funcionario_<%= attr[0]%>" name="funcionario[<%= attr[0]%>]" type="checkbox" value="<%= attr[2] ? 1 : 0 %>" <%= "checked" if attr[2] %> />
 -->  
   <div class="field">
    <%= f.check_box(attr[0]) %>
</div>

  </div>
  <div class="spacer"></div>
<% end %>

<div class="spacer"></div>


<label>
<span class="small">Observacao</span>
</label>
<%= f.text_field :observacao, :size => 70 %>


<div class="spacer"></div>

<label>Justificativa para Externo com Ramal ou Office ?

</label>
<div class="field">
    <%= f.text_field :justificativaExtComOffice365, :size => 70 %>
</div>
<div class="spacer"></div>
<label>Login Bloqueado ?
<div class="spacer"></div>
</label>
<div class="field">
  <% if can? :admin, :all  %>
       <%= f.check_box :loginBloqueado %>
   <% else %>
       <%= f.check_box :loginBloqueado, :disabled => "disabled" %>
    <% end %>
</div>
<div class="spacer"></div>

<label>Justificativa para Login Bloqueado ?

</label>
<div class="field">
    <% if can? :admin, :all  %>
      <%= f.text_field :justificativaLoginBloqueado, :size => 70   %>
    <% else %>
      <%= f.text_field :justificativaLoginBloqueado, :size => 70 , :readonly => "true"  %>
    <% end %>
</div>

<div class="spacer"></div>


<div class="actions">
    
<button type="submit" id="SalvarAtributos">Salvar Atributos</button>
</div>
<div class="spacer"></div>
<% end %>

app/views/funcionarios/edit.html.erb
<div id="stylized" class="myform">
<h1><%=@funcionario.Nome%></h1>

<%= render 'form' %>

<%= link_to '[Cancelar]', funcionario_path(@funcionario) %>

app/views/funcionarios/equipe.html.erb
<% title "GAM. Equipe: #{@funcionario.Login}" %>
<div id="stylized" class="myform">
<h1>Equipe e Gestores</h1>


Gestores
<table>
  <tr>
    <th>Login</th>
    <th>Nome</th>
    <th>Ramal</th>
    <th>Identidades</th>
    <th>Atributos Especiais</th>
   
  </tr>

<% @gestores.reverse_each do |funcionario| %>
  <tr>
        <td><%= link_to funcionario[0], equipe_path(funcionario[0])  %></td> 
    <td><%= link_to funcionario[1], "/GestaoUsuarios?search=#{funcionario[0]}", :target => "_blank"  %></td>
    <td><%= ramal_to_sip(funcionario[3]).html_safe %>
    <td><%= link_to 'Identidades', identities_path(funcionario[0]), :target => "_blank" %></td>
    <td><%= link_to 'Atributos Especiais', funcionario_path(funcionario[0]), :target => "_blank" %></td>
  </tr>
<% end %>
</table>


Equipe
<table>
  <tr>
    <th>Login</th>
    <th>Nome</th>
   <th>Ramal</th>
    <th>Identidades</th>
    <th>Atributos Especiais</th>
  </tr>

<% @equipe.each do |funcionario| %>
  <tr>
    <td><%= link_to funcionario[0], equipe_path(funcionario[0])  %></td> 
    <td><%= link_to funcionario[1], "/GestaoUsuarios?search=#{funcionario[0]}", :target => "_blank"  %></td>
    <td><%= ramal_to_sip(funcionario[2]).html_safe %></td>
    <td><%= link_to 'Identidades', identities_path(funcionario[0]), :target => "_blank" %></td>
    <td><%= link_to 'Atributos Especiais', funcionario_path(funcionario[0]), :target => "_blank" %></td>
  </tr>
<% end %>
</table>

<style>
#sampleDiv{
  width: 80%;
  word-wrap:break-word;
}
</style>

Logins:
<div id="sampleDiv">

<%= @logins %>
</div>
<br />
</div>

app/views/funcionarios/index.html.erb
<h1>Listing funcionarios</h1>

<%= will_paginate(@funcionarios) %>


<table>
  <tr>
    <th>Login</th>
    <th>Matricula</th>
    <th>Nome</th>
    <th>Dataadmissao</th>
    <th>Datademissao</th>
    <th>Email</th>
    <th>Cpf</th>
    <th>Identidade</th>
    <th>Codigocc</th>
    <th>Nomecc</th>
    <th>Nometipocc</th>
    <th>Gestor</th>
    <th>Codigosecao</th>
    <th>Nomelocaltrabalho</th>
    <th>Nomecidadetrabalho</th>
    <th>Cctorre</th>
    <th>Desccctorre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @funcionarios.each do |funcionario| %>
  <tr>
    <td><%= funcionario.Login %></td>
    <td><%= funcionario.Matricula %></td>
    <td><%= funcionario.Nome %></td>
    <td><%= funcionario.DataAdmissao %></td>
    <td><%= funcionario.DataDemissao %></td>
    <td><%= funcionario.Email %></td>
    <td><%= funcionario.CPF %></td>
    <td><%= funcionario.Identidade %></td>
    <td><%= funcionario.CodigoCC %></td>
    <td><%= funcionario.NomeCC %></td>
    <td><%= funcionario.NomeTipoCC %></td>
    <td><%= funcionario.NomeGestor %></td>
    <td><%= funcionario.CodigoSecao %></td>
    <td><%= funcionario.NomeLocalTrabalho %></td>
    <td><%= funcionario.NomeCidadeTrabalho %></td>
    <td><%= funcionario.CCTorre %></td>
    <td><%= funcionario.DescCCTorre %></td>
    <td><%= link_to 'Show', funcionario %></td>
   
  </tr>
<% end %>
</table>

<br />

app/views/funcionarios/new.html.erb
<h1>New funcionario</h1>

<%= render 'form' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<% title "GAM. Funcionario: #{@funcionario.Login}" %>
<div id="stylized" class="myform">
<p id="notice"><%= notice %><br>

<b>Login: </b><%= @funcionario.Login %>
<br>
<b>Matricula: </b><%= @funcionario.Matricula %>
<br>
<b>Nome: </b><%= @funcionario.Nome %>
<br>
<b>Cipa: </b><%= @funcionario.cipa ? "Sim" : "Nao" %>
<br>
<b>Brigadista: </b><%= @funcionario.brigadista ? "Sim" : "Nao" %>
<br>
<b>Sem Estacao: </b><%= @funcionario.semEstacao ? "Sim" : "Nao" %>
<br>
<b>Afastado: </b><%= @funcionario.afastado ? "Sim" : "Nao" %>
<br>
<b>Data Inicio Afastamento: </b><%= @funcionario.DataInicioAfastamento  %>
<br>
<b>Data Final Afastamento: </b><%= @funcionario.DataFinalAfastamento  %>
<br>
<b>Observacao: </b><b><%= @funcionario.observacao%> </b> 
<br>
<b>Tem Ramal sendo externo: </b><%= @funcionario.ramalSendoExterno ? "Sim" : "Nao" %>
<br> 
<b>Justificativa para Externo ter Office365 ou Ramal: </b> <%= @funcionario.justificativaExtComOffice365%> 
<br>
<b>Login Bloqueado: </b><%= @funcionario.loginBloqueado ? "Sim" : "Nao" %>
<br> 
<b>Justificativa para Login Bloqueado: </b> <%= @funcionario.justificativaLoginBloqueado%> 
<br>

<% @attrs.each do |attr| %>
<b><%= attr[1] %> : </b><%= attr[2] ? "Sim" : "Nao" %>
<br>
<% end %>


</div>
  
<%= link_to '[Listagem]', funcionarios_path %> |
<%= link_to '[Editar]', edit_funcionario_path(@funcionario) %>